#!/bin/bash

# Set up some things
TOKEN_TMPDIR="${TMPDIR:-/tmp}"
TOKEN_CACHE="$TOKEN_TMPDIR/bw.token"
USER_ONLY=false
PASS_ONLY=false

# Sometimes we just want one thing
if [ "$1" = "pass-only" ]; then
  PASS_ONLY=true
elif [ "$1" = "user-only" ]; then
  USER_ONLY=true
fi

# Parse out URL and log to the browser
URL=$(echo "$QUTE_URL" | awk -F/ '{print $3}' | sed 's/www.//g')
echo "message-info 'Looking for password for $URL'" >> "$QUTE_FIFO"

# Get session token, or log in if missing/invalid
if [ -f "$TOKEN_CACHE" ]; then
  TOKEN=$(cat "$TOKEN_CACHE")
  bw unlock --check --session "$TOKEN" | rg 'unlocked' >> /dev/null
  UNLOCKED=$(echo $?)
  if [ $UNLOCKED -ne 0 ]; then
    TOKEN=$(bw unlock $(fuzzel --dmenu -l 0 --password -p "Master password: ") --raw)
    echo "$TOKEN" > "$TOKEN_CACHE"
  fi
else
  TOKEN=$(bw unlock $(fuzzel --dmenu -l 0 --password -p "Master password: ") --raw)
  echo "$TOKEN" > "$TOKEN_CACHE"
fi

if [ -z "$TOKEN" ]; then
  echo "message-error 'Could not get a token from BW'" >> "$QUTE_FIFO"
  exit 1
fi

# Get username/password pair
if [ -n "$TOKEN" ]; then
  echo "message-info ''"
  # Fetch from API
  bw sync
  CACHE=$(bw list items --url="$URL" --session="$TOKEN")

  # Get the username we want
  COUNT=$(echo "$CACHE" | jq '. | length')
  if [ $COUNT -eq 1 ]; then
    USERNAME_ID=$(echo "$CACHE" | jq -r '.[0].login.id')
  elif [ $COUNT -eq 0 ]; then
    echo "message-error 'No entry found for $URL'" >> "$QUTE_FIFO"
    exit 1
  else
    index=$(echo "$CACHE" | jq -r '.[] | .name' | fuzzel --dmenu -p "Select Entry: " --index)
    USERNAME_ID=$(echo "$CACHE" | jq --arg idx "$index" -r '.[$idx|tonumber].id')
  fi

  # Get the password we want
  PASSWORD=$(echo "$CACHE" | jq --arg id "$USERNAME_ID" -r '.[] | select(.id == $id) | .login.password')
  USERNAME=$(echo "$CACHE" | jq --arg id "$USERNAME_ID" -r '.[] | select(.id == $id) | .login.username')

  # Do something with the credentials
  if [ "$PASS_ONLY" = true ]; then
    echo -ne "$PASSWORD" | wl-copy
    echo "message-info 'Pasted password into clipboard'" >> "$QUTE_FIFO"
  elif [ "$USER_ONLY" = true ]; then
    echo -ne "$USERNAME" | wl-copy
    echo "message-info 'Pasted username into clipboard'" >> "$QUTE_FIFO"
  else
    echo "fake-key $USERNAME<tab>$PASSWORD" >> "$QUTE_FIFO"
  fi
fi
